image: golang:1.12

stages:
  - test

before_script:
  # Install global go tools
  - go install golang.org/x/lint/golint
  - go get github.com/jstemmer/go-junit-report

test:
  stage: test
  script:
    - golint -set_exit_status ./...
    - go test -v -coverprofile=cover.out -timeout 10s -race ./... | tee >(go-junit-report > report.xml)
    - go tool cover -func cover.out
  coverage: '/^total:\t+\(statements\)\t+(\d+\.\d+)%/'
  artifacts:
    reports:
      junit:
        - report.xml
    expire_in: 1 week
